### ISSUE TITLE
The Cutter argument overlap causes an error for any value other than  the default of none.

### ISSUE THREAD

**Issue by JeffreyYStewart** [scottkleinman/lexos#17]
Setting an overlap value for Ginsu.split_doc() threw the error `AttributeError: 'Ginsu' object has no attribute 'split_overlap'` on line 46 of cutter.\_\_init\_\_.py   
   
Setting an overlap value for Machete.split() threw the error `UnboundLocalError: local variable 'segments' referenced before assignment` on line 514 of cutter.\_\_init\_\_.py   
   
I have not attempted to set an overlap value on any other cutter functions.

**Comment by scottkleinman** [comment]
Cutter has now been refactored, which should have fixed the remaining bugs. Any further problems should be dealt with in another issue.
