### ISSUE TITLE
Tokenizer.doc_from_ngrams is not working

### ISSUE THREAD

**Issue by JeffreyYStewart** [scottkleinman/lexos#20]
Calling `tokenizer.doc_from_ngrams` produces an error indicating that it does  not recognize the language model, even for models it should recognize.

I am not 100% certain on what exactly the problem is, but I seem to have come up with a fix for it. I added `disable: List[str] = []` and `exclude: List[str] = []` as arguments and changed line 223 of `tokenizer.__init__.py` from `nlp = _load_model(model)` to `nlp = _load_model(model, disable=disable, exclude=exclude)`

**Comment by scottkleinman** [comment]
This bug is only fixed for the `splitn()` method. Right now, the other methods are trying to call the same overlap function, but a different algorithm is probably required to handle cases such as a fixed number of segments. This needs further investigation.

**Comment by scottkleinman** [comment]
My comment above appears to have been for the wrong issue (something related to Cutter). Since Cutter has been refactored in [127d810cdb1107ed25dcfb809dd7edf7b343cc1a](https://github.com/scottkleinman/lexos/commit/127d810cdb1107ed25dcfb809dd7edf7b343cc1a), I think this issue can be closed.
