### ISSUE TITLE
scrubber.remove.digits leaves spaces

### ISSUE THREAD

**Issue by JeffreyYStewart** [scottkleinman/lexos#6]
The scrubber tutorial indicates that scrubber.remove.digits should remove the space a digit occupies when it removes. This is not currently the case.  
This is the example from the tutorial (without the other pipeline steps):  
```scrubbed_text = remove_digits("Lexos is the number 12 text analysis tool.", only= "1")```  
  
The output indicated by the tutorial is: ```"Lexos is the number 2 text analysis tool"```  
However, the true output is:                  ```"Lexos is the number  2 text analysis tool"```
  
The space that the "1" occupied was not removed.

**Comment by mleblanc321** [comment]
@JeffreyYStewart: can you see why in the scrubber code?

**Comment by JeffreyYStewart** [comment]
Yes I can, but I am not sure if the mistake is in the documentation or the code. Do we want the numbers to be removed without leaving a space or do we want to leave the space?

**Comment by mleblanc321** [comment]
fair Q ...

**Comment by scottkleinman** [comment]
The documentation probably needs some tweaking, but I think there is a bug in the code:

```python
return str(re.sub(pattern, r" ", text))
```

There probably shouldn't be a space there. If you want to replace digits with a space, you should use [scrubber.replace.digits](https://scottkleinman.github.io/lexos/api/scrubber/replace/#lexos.scrubber.replace.digits).

Alternatively, we could give `scrubber.remove.digits` as `replace_with_space` parameter (or something like that). This might be a useful convenience, and the user would be more likely to go to `scrubber.replace.digits` if they want to replace digits with something like the default value "_DIGIT_".

**Comment by JeffreyYStewart** [comment]
I think it would make the most sense to have `scrubber.remove.digits` just remove the digit and leave any form of replacing to `scrubber.replace.digits`.
